server.port: 8081

spring:
 application:
  name: WASH-PACK-SERVICE
 config.import: configserver:http://localhost:8888/
 data.mongodb:
  uri: mongodb+srv://jaita:password%401234@jaitacluster.milmndm.mongodb.net/?
  database: WasherDatabase
 mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER